## Name: Nihal Patel
## Student ID: 8945100

## Using Tensorflow

3. Using Tensorflow:
- Calculate the dot product between the same vectors as above (re-define them in Tensorflow) (1.5 points)
- Calculate the matrix multiplication of the same matrics as above (re-define them in Tensorflow) (1.5 points)

### 1. Calculate the dot product between the same vectors as above (re-define them in Tensorflow)

In [3]:
# First, we will import necessary libraries
import tensorflow as tf

In [6]:
# We will first define two vectors

vector1 = tf.constant([10,20,30])
vector2 = tf.constant([40,50,60])

# We will now calculate the Dot product of the above created 2 vectors
dotProduct = tf.tensordot(vector1, vector2, axes=1)
print("Vector 1:\n",vector1)
print("Vector 2:\n",vector2)
print("\n")
print("The Dot product of 2 vectors is as below:\n",dotProduct)

Vector 1:
 tf.Tensor([10 20 30], shape=(3,), dtype=int32)
Vector 2:
 tf.Tensor([40 50 60], shape=(3,), dtype=int32)


The Dot product of 2 vectors is as below:
 tf.Tensor(3200, shape=(), dtype=int32)


We have used tf.constant() function to create TensorFlow constant tensors for vector1 and vector2. tf.tensordot() function is used to calculate the dot product of the two vectors. The axes parameter is set to 1 to indicate that the dot product should be calculated along the second axis which also represents the elements of the vectors. The result is stored in dotProduct variable which gives output as tf.Tensor(3200, shape=(), dtype=int32)

### 2. Calculate the matrix multiplication of the same matrics as above (re-define them in Tensorflow)

In [7]:
# We will define the two matrices
matrix1 = tf.constant([[10, 20], [30, 40]])
matrix2 = tf.constant([[50, 60], [70, 80]])

# We will calculate the matrix multiplication
matrixProduct = tf.matmul(matrix1, matrix2)
print("Matrix 1:\n",matrix1)
print("Matrix 2:\n",matrix2)
print("\n")
print("The Matrix multiplication of 2X2 Matrix is:\n",matrixProduct)

Matrix 1:
 tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)
Matrix 2:
 tf.Tensor(
[[50 60]
 [70 80]], shape=(2, 2), dtype=int32)


The Matrix multiplication of 2X2 Matrix is:
 tf.Tensor(
[[1900 2200]
 [4300 5000]], shape=(2, 2), dtype=int32)


We have used the tf.matmul() function to calculate the matrix multiplication of the two matrices. The result is stored in the matrixProduct variable which gives us output as 
tf.Tensor(
[[1900 2200]
 [4300 5000]], shape=(2, 2), dtype=int32)