## Lab 8 - A Dot product and a Matrix Multiplication in PyTorch and Tensorflow

## Name: Nihal Patel
## Student ID: 8945100

1. Setup Tensorflow and PyTorch based on the instructions in ./setup/README.md

2. Using PyTorch:
- Calculate the dot product between two vectors each of length 3 (1.5 points)
- Calculate the matrix multiplication of two 2-dimensional matrices, each with a size of (2,2) (1.5 points)

3. Using Tensorflow:
- Calculate the dot product between the same vectors as above (re-define them in Tensorflow) (1.5 points)
- Calculate the matrix multiplication of the same matrics as above (re-define them in Tensorflow) (1.5 points)

Note: You can submit this as two separate notebooks and HTMLs, or as a single notebook and an HTML (if you choose a single notebook, you will need to switch between the PyTorch and Tesorflow kernels).

## Using Pytorch

### 1. Calculate the dot product between two vectors each of length 3

In [1]:
# First, we will import necessary libraries
import torch

In [2]:
# We will first define two vectors

vector1 = torch.tensor([10,20,30])
vector2 = torch.tensor([40,50,60])

# We will now calculate the Dot product of the above created 2 vectors
dotProduct = torch.dot(vector1, vector2)
print("Vector 1:\n",vector1)
print("Vector 2:\n",vector2)
print("\n")
print("The Dot product of 2 vectors is as below:\n",dotProduct)

Vector 1:
 tensor([10, 20, 30])
Vector 2:
 tensor([40, 50, 60])


The Dot product of 2 vectors is as below:
 tensor(3200)


In the above code, we have used torch.tensor(). It refers to Pytorch tensors for vector1 and vector2. The torch.dot() is used to calculate the dot product of both the vectors. On calculating, we get the Final dot product as 3200 for vector1 and vector2.

### 2. Calculate the matrix multiplication of two 2-dimensional matrices, each with a size of (2,2)

In [7]:
# We will define the two matrices
matrix1 = torch.tensor([[10, 20], [30, 40]])
matrix2 = torch.tensor([[50, 60], [70, 80]])

# We will calculate the matrix multiplication
matrixProduct = torch.matmul(matrix1, matrix2)
print("Matrix 1:\n",matrix1)
print("Matrix 2:\n",matrix2)
print("\n")
print("The Matrix multiplication of 2X2 Matrix is:\n",matrixProduct)

Matrix 1:
 tensor([[10, 20],
        [30, 40]])
Matrix 2:
 tensor([[50, 60],
        [70, 80]])


The Matrix multiplication of 2X2 Matrix is:
 tensor([[1900, 2200],
        [4300, 5000]])


We have used the torch.matmul() function to calculate the matrix multiplication of the two matrices, and the result is stored in the matrixProduct variable. The final matrix product we are getting is  
tensor([[1900, 2200],
        [4300, 5000]])